# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Vishal Sharma
title: Student/Software Engineer
email: makeavish786@gmail.com
website: www.vishalsharma.ml

# Social links
twitter_username: makeavish11
github_username:  makeavish
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: makeavish11
linkedin_username: makeavish
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Vishal and I'm a student. I have experience in Data Analytics, ML, Algorithms, etc. I have worked at a number of companies gaining teamwork and leadership skills.
  I have worked with a range of different languages and frameworks and I am always looking for opportunities to work with something new. The things that I currently have the most experience working with are: <mark>Python</mark>, <mark>Android</mark>, <mark>git</mark>, <mark>MySQL</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: When I'm not at my Desk
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Reading
   - Basketball
   - Badminton
   - Researching about Professions and People

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
